apiVersion: v1
kind: Service
metadata:
  labels:
    app: stellio-api-gateway
  name: api-gateway
spec:
  #type: NodePort
  type: ClusterIP
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: stellio-api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stellio-api-gateway
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: stellio-api-gateway
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: stellio-api-gateway
    spec:
      nodeSelector: {}
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: stellio-conf
              key: ENVIRONMENT
        image: 'stellio/stellio-api-gateway:latest'
        name: stellio-api-gateway
        ports:
        - containerPort: 8080
          name: api-gateway
        resources: {}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Always